language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  - "pip install -U pip"
  - "pip install -r requirements.txt"
  - "pip install ."

# command to run tests
script:
  - pytest

# safelist
branches:
  only:
  - master
